services:

  standalone:
    build:
      context: .
      dockerfile: infra/Dockerfile.standalone
    ports:
      - 8080:3000
    environment:
      - MONITOR_INTERVAL_MINUTES=1
      - DATABASE_PATH=/app/data/ping-status.db
    volumes:
      - ./data:/app/data